services:
  go:
    build: ./Go
    ports:
      - "8080:8080"
    depends_on:
      - python

  python:
    build: ./Python
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"