name: Closetly-CD

on:
  workflow_run:
    workflows: ["Closetly-CI"]
    types:
      - completed

jobs:
  deploy-go:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      - self-hosted
      - go

    steps:
      - name: Deploy Go
        run: |
          docker pull kkuro5001/closetly-go:latest

          docker stop closetly-go || true
          docker rm closetly-go || true

          docker run -d \
            --name closetly-go \
            --security-opt apparmor=unconfined \
            -p 8080:8080 \
            -e PYTHON_API_URL=http://192.168.11.37:8000 \
            --restart unless-stopped \
            kkuro5001/closetly-go:latest

  deploy-python:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      - self-hosted
      - python

    steps:
      - name: Deploy Python
        run: |
          docker pull kkuro5001/closetly-python:latest

          docker stop closetly-python || true
          docker rm closetly-python || true

          docker run -d \
            --name closetly-python \
            -p 8000:8000 \
            --restart unless-stopped \
            kkuro5001/closetly-python:latest

  deploy-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      - self-hosted
      - frontend

    steps:
      - name: Check Frontend Runner
        run: |
          echo "=== HOST ==="
          hostname

          echo "=== USER ==="
          whoami

          echo "=== GROUPS ==="
          id

          echo "=== DOCKER ==="
          docker ps

      - name: Deploy Frontend
        run: |
          docker pull kkuro5001/closetly-frontend:latest

          docker stop closetly-frontend || true
          docker rm closetly-frontend || true

          docker run -d \
            --name closetly-frontend \
            -p 80:80 \
            --security-opt apparmor=unconfined \
            --restart unless-stopped \
            kkuro5001/closetly-frontend:latest