name: Closetly-CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    #Githubで作成した環境名を指定
    #environment: productions

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Test Go
      working-directory: Go
      run: go test ./...

    - name: Test Python
      working-directory: Python
      run: python -m compileall .

    - name: Build Go
      run: |
        docker build \
          -t "${{ secrets.DOCKERHUB_USERNAME }}/closetly-go:${{ github.sha }}" \
          ./Go

        #Docker image clean 最新の5個だけ残して削除
        # - name: Clean up old Go images
        #   uses: vscodedev/docker-hub-cleanup-action@v1
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     token: ${{ secrets.DOCKERHUB_TOKEN }}
        #     repository: closetly-go
        #     keep: 5

        # Docker image clean 最新の5個だけ残して削除
        # - name: Clean up old Python images
        #   uses: vscodedev/docker-hub-cleanup-action@v1
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     token: ${{ secrets.DOCKERHUB_TOKEN }}
        #     repository: closetly-python
        #     keep: 5